defaults:
  - _self_

environment:
  name: "FrozenLake-v1"
  render_mode: "ansi"
  is_slippery: true
  map_name: "8x8"
  reward_mode: "penalty_for_death"

network:
  input_dim: 64   # Adapté à FrozenLake 4x4
  hidden_dim: 32
  output_dim: 4

hyperparameters:
  optimizer_type: "adam"
  mode_training: true
  state_shape: [1, 64]
  learning_rate: 0.001
  clip_grad_norm: 3
  discount_factor: 0.99
  max_episodes: 10000
  memory_capacity: 10000
  batch_size: 64
  update_frequency: 1
  update_mode: "soft_update"
  exploration_mode: "epsilon-greedy"
  tau: 0.1
  nu: 1
  tau_softmax: 5
  epsilon: 1
  epsilon_min: 0.01
  epsilon_decay: 0.999
  grad_clipping_method: null
  grad_clipping_threshold: 0